server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Sayfa bulunamazsa index.html'e yönlendir (Flutter routing için şart)
        try_files $uri $uri/ /index.html;
    }

    # Statik dosyaları önbellekle (Opsiyonel performans ayarı)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
