import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/note_model.dart';
import 'notification_trigger_service.dart';

class NotesService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  /// Get current user's coupleId
  Future<String?> _getCoupleId() async {
    final uid = _auth.currentUser?.uid;
    if (uid == null) return null;

    final userDoc = await _db.collection('users').doc(uid).get();
    return userDoc.data()?['coupleId'] ?? uid;
  }

  /// Get current user's name
  Future<String?> _getUserName() async {
    final uid = _auth.currentUser?.uid;
    if (uid == null) return null;

    final userDoc = await _db.collection('users').doc(uid).get();
    return userDoc.data()?['name'] ?? 'Unknown';
  }

  /// Stream of all notes for the couple
  Stream<List<Note>> getNotesStream({int? limit}) async* {
    final coupleId = await _getCoupleId();
    if (coupleId == null) {
      yield [];
      return;
    }

    var query = _db
        .collection('couples')
        .doc(coupleId)
        .collection('notes')
        .orderBy('createdAt', descending: true);

    if (limit != null) {
      query = query.limit(limit);
    }

    yield* query.snapshots().map(
          (snapshot) => snapshot.docs.map((doc) => Note.fromFirestore(doc)).toList(),
        );
  }

  /// Add a new note
  Future<String?> addNote({
    required String message,
    String? emoji,
  }) async {
    try {
      final coupleId = await _getCoupleId();
      if (coupleId == null) return 'User not authenticated';

      final userName = await _getUserName();
      final uid = _auth.currentUser?.uid;

      final noteData = Note(
        id: '', // Generated by Firestore
        message: message,
        authorId: uid ?? '',
        authorName: userName ?? 'Unknown',
        emoji: emoji ?? '❤️',
        createdAt: DateTime.now(),
      ).toMap(); // Does not include 'id'

      await _db
          .collection('couples')
          .doc(coupleId)
          .collection('notes')
          .add(noteData);

      // Trigger Notification
      await NotificationTriggerService.triggerNotification(
        coupleId: coupleId,
        title: 'Yeni Not',
        body: '$userName: $message',
        data: {'type': 'note'},
      );

      return null; // Success
    } catch (e) {
      return 'Failed to add note: $e';
    }
  }

  /// Delete a note (only if user is the author)
  Future<String?> deleteNote(String noteId) async {
    try {
      final coupleId = await _getCoupleId();
      if (coupleId == null) return 'User not authenticated';

      final uid = _auth.currentUser?.uid;

      // Check if user is the author
      final noteDoc = await _db
          .collection('couples')
          .doc(coupleId)
          .collection('notes')
          .doc(noteId)
          .get();

      if (!noteDoc.exists) return 'Note not found';

      final note = Note.fromFirestore(noteDoc);
      if (note.authorId != uid) {
        return 'You can only delete your own notes';
      }

      await _db
          .collection('couples')
          .doc(coupleId)
          .collection('notes')
          .doc(noteId)
          .delete();

      // Trigger Notification
      await NotificationTriggerService.triggerNotification(
        coupleId: coupleId,
        title: 'Not Silindi',
        body: 'Bir not silindi.',
      );

      return null; // Success
    } catch (e) {
      return 'Failed to delete note: $e';
    }
  }

  /// Get note count
  Future<int> getNoteCount() async {
    try {
      final coupleId = await _getCoupleId();
      if (coupleId == null) return 0;

      final notesSnapshot = await _db
          .collection('couples')
          .doc(coupleId)
          .collection('notes')
          .get();

      return notesSnapshot.docs.length;
    } catch (e) {
      return 0;
    }
  }
}
